In [2]:
import pandas as pd

In [56]:
data = {
    'Age': [22,35,28,45,31,26,40,29,52,33,24,38,47,30,42,27,36,50,23,34,41,32,55,28,39,25,44,37,48,30],

    'Income': [25000,60000,40000,80000,50000,32000,70000,45000,90000,55000,28000,65000,75000,42000,85000,35000,58000,95000,30000,52000,72000,48000,100000,38000,68000,27000,78000,62000,88000,46000],

    'Employment_Years': [1,10,4,15,7,2,12,5,20,8,1,11,16,4,14,3,9,19,1,6,13,7,21,3,10,2,17,12,18,5],

    'Credit_Scre': [620,750,680,800,710,590,730,650,820,700,580,760,790,640,810,610,720,830,600,690,770,670,840,630,740,570,780,710,805,660],

    'Loan+Amount': [100000,300000,200000,500000,250000,150000,400000,180000,550000,280000,120000,350000,450000,220000,500000,160000,300000,600000,100000,240000,380000,200000,550000,170000,320000,130000,420000,280000,480000,210000],

    'Long_Term': [24,36,36,60,48,24,60,36,60,48,24,36,60,36,48,24,36,60,24,48,60,36,60,24,48,24,60,36,48,36],

    'Exisitng_Loans': [1,0,2,0,1,3,0,2,0,1,2,0,1,3,0,2,1,0,3,1,0,2,0,2,1,3,0,1,0,2],

    'Dependents': [0,2,1,3,2,0,2,1,3,2,0,1,2,1,3,0,2,4,1,2,3,1,2,0,3,1,2,3,1,2],

    'Educations': ['Graduate','Graduate','Not Graduate','Graduate','Graduate',
                   'Not Graduate','Graduate','Graduate','Graduate','Graduate',
                   'Not Graduate','Graduate','Graduate','Not Graduate','Graduate',
                   'Graduate','Graduate','Graduate','Not Graduate','Graduate',
                   'Graduate','Not Graduate','Graduate','Graduate','Graduate',
                   'Not Graduate','Graduate','Graduate','Graduate','Not Graduate'],

    'Self_Employed': ['No','No','Yes','No','Yes',
                      'No','No','Yes','No','No',
                      'Yes','No','No','Yes','No',
                      'Yes','No','No','Yes','No',
                      'No','Yes','No','Yes','No',
                      'Yes','No','No','Yes','No'],

    'Loan_Approved': [0,1,0,1,1,0,1,0,1,1,
                      0,1,1,0,1,0,1,1,0,1,
                      1,0,1,0,1,0,1,1,1,0]
}

In [57]:
df = pd.DataFrame(data)

In [58]:
df.head()

,Age,Income,Employment_Years,Credit_Scre,Loan+Amount,Long_Term,Exisitng_Loans,Dependents,Educations,Self_Employed,Loan_Approved
0,22,25000,1,620,100000,24,1,0,Graduate,No,0
1,35,60000,10,750,300000,36,0,2,Graduate,No,1
2,28,40000,4,680,200000,36,2,1,Not Graduate,Yes,0
3,45,80000,15,800,500000,60,0,3,Graduate,No,1
4,31,50000,7,710,250000,48,1,2,Graduate,Yes,1

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               30 non-null     int64
 1   Income            30 non-null     int64
 2   Employment_Years  30 non-null     int64
 3   Credit_Scre       30 non-null     int64
 4   Loan+Amount       30 non-null     int64
 5   Long_Term         30 non-null     int64
 6   Exisitng_Loans    30 non-null     int64
 7   Dependents        30 non-null     int64
 8   Educations        30 non-null     object
 9   Self_Employed     30 non-null     object
 10  Loan_Approved     30 non-null     int64
dtypes: int64(9), object(2)
memory usage: 2.7+ KB

In [60]:
df.isnull().sum()

Age                 0
Income              0
Employment_Years    0
Credit_Scre         0
Loan+Amount         0
Long_Term           0
Exisitng_Loans      0
Dependents          0
Educations          0
Self_Employed       0
Loan_Approved       0
dtype: int64

In [61]:
df.columns = [
    "Age",
    "Income",
    "Employment_Years",
    "Credit_Score",
    "Loan_Amount",
    "Loan_Term",
    "Existing_Loans",
    "Dependents",
    "Education",
    "Self_Employed",
    "Loan_Approved"
]

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               30 non-null     int64
 1   Income            30 non-null     int64
 2   Employment_Years  30 non-null     int64
 3   Credit_Score      30 non-null     int64
 4   Loan_Amount       30 non-null     int64
 5   Loan_Term         30 non-null     int64
 6   Existing_Loans    30 non-null     int64
 7   Dependents        30 non-null     int64
 8   Education         30 non-null     object
 9   Self_Employed     30 non-null     object
 10  Loan_Approved     30 non-null     int64
dtypes: int64(9), object(2)
memory usage: 2.7+ KB

In [63]:
df['Education'] = df['Education'].map({'Not Graduate':0, 'Graduate':1})

In [64]:
df['Self_Employed'] = df['Self_Employed'].map({'No':0,'Yes':1})
df['Self_Employed'].unique()

array([0, 1])

In [65]:
df.head()

,Age,Income,Employment_Years,Credit_Score,Loan_Amount,Loan_Term,Existing_Loans,Dependents,Education,Self_Employed,Loan_Approved
0,22,25000,1,620,100000,24,1,0,1,0,0
1,35,60000,10,750,300000,36,0,2,1,0,1
2,28,40000,4,680,200000,36,2,1,0,1,0
3,45,80000,15,800,500000,60,0,3,1,0,1
4,31,50000,7,710,250000,48,1,2,1,1,1

In [66]:
df.describe()

,Age,Income,Employment_Years,Credit_Score,Loan_Amount,Loan_Term,Existing_Loans,Dependents,Education,Self_Employed,Loan_Approved
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,35.700000,57966.666667,9.200000,708.500000,303000.000000,42.000000,1.133333,1.666667,0.733333,0.366667,0.600000
std,9.146886,21900.217812,6.216774,81.443338,148490.101841,13.645765,1.074255,1.093345,0.449776,0.490133,0.498273
min,22.000000,25000.000000,1.000000,570.000000,100000.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28.250000,40500.000000,4.000000,642.500000,185000.000000,36.000000,0.000000,1.000000,0.250000,0.000000,0.000000
50%,34.500000,56500.000000,8.500000,710.000000,280000.000000,36.000000,1.000000,2.000000,1.000000,0.000000,1.000000
75%,41.750000,74250.000000,13.750000,777.500000,415000.000000,57.000000,2.000000,2.000000,1.000000,1.000000,1.000000
max,55.000000,100000.000000,21.000000,840.000000,600000.000000,60.000000,3.000000,4.000000,1.000000,1.000000,1.000000

In [67]:
df.shape

(30, 11)

In [68]:
x = df.drop('Loan_Approved', axis=1)
y = df['Loan_Approved']

Training and Testing and Spliting

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [71]:
print(x_train.shape)

(24, 10)

In [72]:
print(x_test.shape)

(6, 10)

  Logisitc Regression

In [73]:
from sklearn.linear_model import LogisticRegression

Training the model

In [74]:
model = LogisticRegression(max_iter = 1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [75]:
pred = model.predict(x_test)

In [76]:
from sklearn.metrics import accuracy_score

In [77]:
accuracy = accuracy_score(y_test,pred)

In [78]:
print('Accuracy', accuracy)

Accuracy 1.0